-- PostgreSQL 18 — 商家入驻信息 (merchants)
-- Depends on: 00_moonite_touch_updated_at.sql

CREATE TABLE public.merchants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name varchar(255) NOT NULL DEFAULT '',
  contact_name varchar(128) NOT NULL DEFAULT '',
  contact_mobile varchar(32) NOT NULL DEFAULT '',
  company_type varchar(32) NOT NULL DEFAULT '',
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz NULL
);

CREATE TRIGGER merchants_touch_updated_at
  BEFORE UPDATE ON public.merchants
  FOR EACH ROW
  EXECUTE FUNCTION public.moonite_touch_updated_at();

COMMENT ON TABLE public.merchants IS '商家入驻信息';
COMMENT ON COLUMN public.merchants.id IS '主键，自增';
COMMENT ON COLUMN public.merchants.company_name IS '公司名';
COMMENT ON COLUMN public.merchants.contact_name IS '联系人';
COMMENT ON COLUMN public.merchants.contact_mobile IS '联系人手机号';
COMMENT ON COLUMN public.merchants.company_type IS '公司类型（如自营、非自营等）';
COMMENT ON COLUMN public.merchants.is_deleted IS '是否删除';
COMMENT ON COLUMN public.merchants.created_at IS '创建时间，插入时自动赋值';
COMMENT ON COLUMN public.merchants.updated_at IS '更新时间，更新时自动赋值';
COMMENT ON COLUMN public.merchants.deleted_at IS '删除时间（软删时记录）';
