-- PostgreSQL 18 — 订单优惠 (order_discounts)
-- Depends on: 00_moonite_touch_updated_at.sql, room_orders.sql

CREATE TABLE public.order_discounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NULL REFERENCES public.room_orders (id) ON DELETE SET NULL,
  discount_type varchar(8) NOT NULL DEFAULT '',
  discount_amount numeric(10, 2) NULL,
  coupon_id bigint NULL,
  external_platform varchar(16) NOT NULL DEFAULT '',
  discount_reason varchar(200) NOT NULL DEFAULT '',
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz NULL
);

CREATE TRIGGER order_discounts_touch_updated_at
  BEFORE UPDATE ON public.order_discounts
  FOR EACH ROW
  EXECUTE FUNCTION public.moonite_touch_updated_at();

COMMENT ON TABLE public.order_discounts IS '订单优惠信息（订单关联的优惠券等）';
COMMENT ON COLUMN public.order_discounts.id IS '主键，自增';
COMMENT ON COLUMN public.order_discounts.order_id IS '订单ID';
COMMENT ON COLUMN public.order_discounts.discount_type IS '优惠类型：balance/coupon/group/external';
COMMENT ON COLUMN public.order_discounts.discount_amount IS '优惠金额';
COMMENT ON COLUMN public.order_discounts.coupon_id IS '优惠券ID';
COMMENT ON COLUMN public.order_discounts.external_platform IS '外部券平台：meituan/douyin 等';
COMMENT ON COLUMN public.order_discounts.discount_reason IS '优惠原因';
COMMENT ON COLUMN public.order_discounts.is_deleted IS '是否删除';
COMMENT ON COLUMN public.order_discounts.created_at IS '创建时间，插入时自动赋值';
COMMENT ON COLUMN public.order_discounts.updated_at IS '更新时间，更新时自动赋值';
COMMENT ON COLUMN public.order_discounts.deleted_at IS '删除时间（软删时记录）';
