-- PostgreSQL 18 — 房间信息 (rooms)
-- Depends on: 00_moonite_touch_updated_at.sql, shops.sql

CREATE TABLE public.rooms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id bigint NOT NULL REFERENCES public.shops (id) ON DELETE RESTRICT,
  room_name varchar(255) NOT NULL DEFAULT '',
  room_type varchar(32) NOT NULL DEFAULT '',
  room_area numeric(12, 2) NULL,
  capacity integer NULL,
  base_price numeric(10, 2) NULL,
  renew_price numeric(10, 2) NULL,
  room_status varchar(16) NOT NULL DEFAULT '',
  room_images text[] NOT NULL DEFAULT ARRAY[]::text[],
  description text NOT NULL DEFAULT '',
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz NULL
);

CREATE TRIGGER rooms_touch_updated_at
  BEFORE UPDATE ON public.rooms
  FOR EACH ROW
  EXECUTE FUNCTION public.moonite_touch_updated_at();

COMMENT ON TABLE public.rooms IS '房间信息';
COMMENT ON COLUMN public.rooms.id IS '主键，自增';
COMMENT ON COLUMN public.rooms.shop_id IS '所属店铺ID';
COMMENT ON COLUMN public.rooms.room_name IS '房间名';
COMMENT ON COLUMN public.rooms.room_type IS '房间类型（办公/会议/休息等）';
COMMENT ON COLUMN public.rooms.room_area IS '房间面积';
COMMENT ON COLUMN public.rooms.capacity IS '容量（适用人数）';
COMMENT ON COLUMN public.rooms.base_price IS '房间 1 小时单价';
COMMENT ON COLUMN public.rooms.renew_price IS '续单 1 小时单价';
COMMENT ON COLUMN public.rooms.room_status IS '房间状态（空闲/占用/维修/下线/预订等）';
COMMENT ON COLUMN public.rooms.room_images IS '房间图片列表';
COMMENT ON COLUMN public.rooms.description IS '房间描述';
COMMENT ON COLUMN public.rooms.is_deleted IS '是否删除';
COMMENT ON COLUMN public.rooms.created_at IS '创建时间，插入时自动赋值';
COMMENT ON COLUMN public.rooms.updated_at IS '更新时间，更新时自动赋值';
COMMENT ON COLUMN public.rooms.deleted_at IS '删除时间（软删时记录）';
