-- PostgreSQL 18 — 房间订单 (room_orders)
-- Depends on: 00_moonite_touch_updated_at.sql, users.sql, shops.sql, rooms.sql

CREATE TABLE public.room_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number varchar(50) NOT NULL,
  ref_id bigint NULL REFERENCES public.room_orders (id) ON DELETE SET NULL,
  user_id bigint NULL REFERENCES public.users (id) ON DELETE SET NULL,
  shop_id bigint NULL REFERENCES public.shops (id) ON DELETE SET NULL,
  room_id bigint NULL REFERENCES public.rooms (id) ON DELETE SET NULL,
  order_type varchar(8) NOT NULL DEFAULT '',
  source_platform varchar(8) NOT NULL DEFAULT '',
  start_time timestamptz NULL,
  end_time timestamptz NULL,
  duration_minute integer NOT NULL DEFAULT 0,
  order_price numeric(10, 2) NULL,
  renew_price numeric(10, 2) NULL,
  package_name varchar(50) NOT NULL DEFAULT '',
  package_price numeric(10, 2) NULL,
  package_id bigint NULL,
  total_price numeric(10, 2) NULL,
  pay_amount numeric(10, 2) NULL,
  order_status varchar(8) NOT NULL DEFAULT 'created',
  remark varchar(200) NOT NULL DEFAULT '',
  pay_time timestamptz NULL,
  finish_time timestamptz NULL,
  cancel_time timestamptz NULL,
  refund_time timestamptz NULL,
  pay_channel varchar(4) NOT NULL DEFAULT '',
  refund_amount numeric(10, 2) NULL,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz NULL
);

CREATE TRIGGER room_orders_touch_updated_at
  BEFORE UPDATE ON public.room_orders
  FOR EACH ROW
  EXECUTE FUNCTION public.moonite_touch_updated_at();

CREATE UNIQUE INDEX room_orders_order_number_uidx
  ON public.room_orders (order_number)
  WHERE is_deleted = false;

COMMENT ON TABLE public.room_orders IS '房间订单';
COMMENT ON COLUMN public.room_orders.id IS '主键，自增';
COMMENT ON COLUMN public.room_orders.order_number IS '生成的订单号';
COMMENT ON COLUMN public.room_orders.ref_id IS '续单时为主订单主键ID，新单为 null';
COMMENT ON COLUMN public.room_orders.user_id IS '下单人ID';
COMMENT ON COLUMN public.room_orders.shop_id IS '门店ID';
COMMENT ON COLUMN public.room_orders.room_id IS '房间ID';
COMMENT ON COLUMN public.room_orders.order_type IS '订单类型：package/hourly';
COMMENT ON COLUMN public.room_orders.source_platform IS '来源平台';
COMMENT ON COLUMN public.room_orders.start_time IS '开始时间';
COMMENT ON COLUMN public.room_orders.end_time IS '结束时间';
COMMENT ON COLUMN public.room_orders.duration_minute IS '总时长，单位分钟';
COMMENT ON COLUMN public.room_orders.order_price IS '房间单价';
COMMENT ON COLUMN public.room_orders.renew_price IS '续单单价';
COMMENT ON COLUMN public.room_orders.package_name IS '套餐名称';
COMMENT ON COLUMN public.room_orders.package_price IS '套餐总价';
COMMENT ON COLUMN public.room_orders.package_id IS '套餐ID';
COMMENT ON COLUMN public.room_orders.total_price IS '总价';
COMMENT ON COLUMN public.room_orders.pay_amount IS '实际付款金额';
COMMENT ON COLUMN public.room_orders.order_status IS '订单状态：created/paid/finished/canceled/refunding/refunded';
COMMENT ON COLUMN public.room_orders.remark IS '下单备注';
COMMENT ON COLUMN public.room_orders.pay_time IS '支付时间';
COMMENT ON COLUMN public.room_orders.finish_time IS '完成时间';
COMMENT ON COLUMN public.room_orders.cancel_time IS '取消时间';
COMMENT ON COLUMN public.room_orders.refund_time IS '退款时间';
COMMENT ON COLUMN public.room_orders.pay_channel IS '支付渠道：wechat/alipay/bank/cash/other';
COMMENT ON COLUMN public.room_orders.refund_amount IS '退款金额，支持部分退款';
COMMENT ON COLUMN public.room_orders.is_deleted IS '是否删除';
COMMENT ON COLUMN public.room_orders.created_at IS '创建时间，插入时自动赋值';
COMMENT ON COLUMN public.room_orders.updated_at IS '更新时间，更新时自动赋值';
COMMENT ON COLUMN public.room_orders.deleted_at IS '删除时间（软删时记录）';
