-- PostgreSQL 18 — 店铺信息 (shops)
-- Depends on: 00_moonite_touch_updated_at.sql, merchants.sql

CREATE TABLE public.shops (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id bigint NOT NULL REFERENCES public.merchants (id) ON DELETE RESTRICT,
  shop_name varchar(255) NOT NULL DEFAULT '',
  contact_name varchar(128) NOT NULL DEFAULT '',
  shop_type varchar(32) NOT NULL DEFAULT '',
  contact_phone varchar(32) NOT NULL DEFAULT '',
  province varchar(64) NOT NULL DEFAULT '',
  province_code varchar(16) NOT NULL DEFAULT '',
  city varchar(64) NOT NULL DEFAULT '',
  city_code varchar(16) NOT NULL DEFAULT '',
  district varchar(64) NOT NULL DEFAULT '',
  district_code varchar(16) NOT NULL DEFAULT '',
  street varchar(255) NOT NULL DEFAULT '',
  street_code varchar(16) NOT NULL DEFAULT '',
  address varchar(255) NOT NULL DEFAULT '',
  latitude double precision NULL,
  longitude double precision NULL,
  geohash varchar(32) NOT NULL DEFAULT '',
  -- Optional PostGIS: add `location geometry(Point, 4326)` after `CREATE EXTENSION postgis`.
  business_status varchar(16) NOT NULL DEFAULT '',
  shop_images text[] NOT NULL DEFAULT ARRAY[]::text[],
  tags text[] NOT NULL DEFAULT ARRAY[]::text[],
  description text NOT NULL DEFAULT '',
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz NULL
);

CREATE TRIGGER shops_touch_updated_at
  BEFORE UPDATE ON public.shops
  FOR EACH ROW
  EXECUTE FUNCTION public.moonite_touch_updated_at();

COMMENT ON TABLE public.shops IS '店铺信息';
COMMENT ON COLUMN public.shops.id IS '主键，自增';
COMMENT ON COLUMN public.shops.merchant_id IS '所属商家ID';
COMMENT ON COLUMN public.shops.shop_name IS '店铺名';
COMMENT ON COLUMN public.shops.contact_name IS '联系人';
COMMENT ON COLUMN public.shops.shop_type IS '门店类型（自营/加盟/共享/品牌联营等）';
COMMENT ON COLUMN public.shops.contact_phone IS '联系人电话';
COMMENT ON COLUMN public.shops.province IS '省';
COMMENT ON COLUMN public.shops.province_code IS '省级行政区划代码';
COMMENT ON COLUMN public.shops.city IS '市';
COMMENT ON COLUMN public.shops.city_code IS '市级行政区划代码';
COMMENT ON COLUMN public.shops.district IS '区/县';
COMMENT ON COLUMN public.shops.district_code IS '区县级行政区划代码';
COMMENT ON COLUMN public.shops.street IS '街道';
COMMENT ON COLUMN public.shops.street_code IS '街道级区划代码';
COMMENT ON COLUMN public.shops.address IS '详细地址';
COMMENT ON COLUMN public.shops.latitude IS '纬度';
COMMENT ON COLUMN public.shops.longitude IS '经度';
COMMENT ON COLUMN public.shops.geohash IS '地理位置 geohash';
COMMENT ON COLUMN public.shops.business_status IS '营业状态（营业、歇业等）';
COMMENT ON COLUMN public.shops.shop_images IS '店铺图片列表';
COMMENT ON COLUMN public.shops.tags IS '标签列表';
COMMENT ON COLUMN public.shops.description IS '门店描述';
COMMENT ON COLUMN public.shops.is_deleted IS '是否删除';
COMMENT ON COLUMN public.shops.created_at IS '创建时间，插入时自动赋值';
COMMENT ON COLUMN public.shops.updated_at IS '更新时间，更新时自动赋值';
COMMENT ON COLUMN public.shops.deleted_at IS '删除时间（软删时记录）';

-- -- PostgreSQL 触发器示例
-- CREATE OR REPLACE FUNCTION sync_shop_location()
-- RETURNS TRIGGER AS $$
-- BEGIN
--   NEW.latitude = ST_Y(NEW.location::geometry);
--   NEW.longitude = ST_X(NEW.location::geometry);
--   NEW.geohash = ST_GeoHash(NEW.location::geometry, 12);
--   RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;

-- CREATE TRIGGER trg_sync_location
-- BEFORE INSERT OR UPDATE ON shop
-- FOR EACH ROW
-- EXECUTE FUNCTION sync_shop_location();
