-- PostgreSQL 18 — 用户信息 (users)
-- Depends on: 00_moonite_touch_updated_at.sql

CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mobile varchar(32) NOT NULL DEFAULT '',
  nickname varchar(128) NOT NULL DEFAULT '',
  avatar varchar(512) NOT NULL DEFAULT '',
  gender integer NOT NULL DEFAULT 0, -- 0: unknown, 1: male, 2: female
  birthday date NULL,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz NULL
);

CREATE TRIGGER users_touch_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW
  EXECUTE FUNCTION public.moonite_touch_updated_at();

COMMENT ON TABLE public.users IS '用户信息';
COMMENT ON COLUMN public.users.id IS '主键，自增';
COMMENT ON COLUMN public.users.mobile IS '手机号';
COMMENT ON COLUMN public.users.nickname IS '昵称';
COMMENT ON COLUMN public.users.avatar IS '头像 URL';
COMMENT ON COLUMN public.users.gender IS '性别：0 未知，1 男，2 女';
COMMENT ON COLUMN public.users.birthday IS '生日';
COMMENT ON COLUMN public.users.is_deleted IS '是否删除';
COMMENT ON COLUMN public.users.created_at IS '创建时间，插入时自动赋值';
COMMENT ON COLUMN public.users.updated_at IS '更新时间，更新时自动赋值';
COMMENT ON COLUMN public.users.deleted_at IS '删除时间（软删时记录）';
