-- PostgreSQL 18 — 用户授权信息 (user_auths)
-- Depends on: 00_moonite_touch_updated_at.sql, users.sql

CREATE TABLE public.user_auths (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users (id) ON DELETE RESTRICT,
  platform varchar(16) NOT NULL DEFAULT '',
  openid varchar(128) NOT NULL DEFAULT '',
  unionid varchar(128) NOT NULL DEFAULT '',
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz NULL
);

CREATE TRIGGER user_auths_touch_updated_at
  BEFORE UPDATE ON public.user_auths
  FOR EACH ROW
  EXECUTE FUNCTION public.moonite_touch_updated_at();

COMMENT ON TABLE public.user_auths IS '用户授权信息（第三方平台绑定）';
COMMENT ON COLUMN public.user_auths.id IS '主键，自增';
COMMENT ON COLUMN public.user_auths.user_id IS '用户ID';
COMMENT ON COLUMN public.user_auths.platform IS '平台（wechat/douyin/kuaishou 等）';
COMMENT ON COLUMN public.user_auths.openid IS '平台 openid';
COMMENT ON COLUMN public.user_auths.unionid IS '平台 unionid';
COMMENT ON COLUMN public.user_auths.is_deleted IS '是否删除';
COMMENT ON COLUMN public.user_auths.created_at IS '创建时间，插入时自动赋值';
COMMENT ON COLUMN public.user_auths.updated_at IS '更新时间，更新时自动赋值';
COMMENT ON COLUMN public.user_auths.deleted_at IS '删除时间（软删时记录）';
