"""init

Revision ID: 46033e1bb323
Revises: 
Create Date: 2026-03-29 09:19:38.008769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46033e1bb323'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchants', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('merchants', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='公司名',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('merchants', 'contact_name',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='联系人',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('merchants', 'contact_mobile',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='联系人手机号',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('merchants', 'company_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='公司类型（如自营、非自营等）',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('merchants', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('merchants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('merchants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('merchants', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='删除时间（软删时记录）',
               existing_nullable=True)
    op.drop_table_comment(
        'merchants',
        existing_comment='商家入驻信息',
        schema=None
    )
    op.alter_column('order_discounts', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('order_discounts', 'order_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='订单ID',
               existing_nullable=True)
    op.alter_column('order_discounts', 'discount_type',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='优惠类型：balance/coupon/group/external',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('order_discounts', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='优惠金额',
               existing_nullable=True)
    op.alter_column('order_discounts', 'coupon_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='优惠券ID',
               existing_nullable=True)
    op.alter_column('order_discounts', 'external_platform',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='外部券平台：meituan/douyin 等',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('order_discounts', 'discount_reason',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='优惠原因',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('order_discounts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('order_discounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_discounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_discounts', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='删除时间（软删时记录）',
               existing_nullable=True)
    op.drop_table_comment(
        'order_discounts',
        existing_comment='订单优惠信息（订单关联的优惠券等）',
        schema=None
    )
    op.alter_column('room_orders', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('room_orders', 'order_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='生成的订单号',
               existing_nullable=False)
    op.alter_column('room_orders', 'ref_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='续单时为主订单主键ID，新单为 null',
               existing_nullable=True)
    op.alter_column('room_orders', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='下单人ID',
               existing_nullable=True)
    op.alter_column('room_orders', 'shop_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='门店ID',
               existing_nullable=True)
    op.alter_column('room_orders', 'room_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='房间ID',
               existing_nullable=True)
    op.alter_column('room_orders', 'order_type',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='订单类型：package/hourly',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('room_orders', 'source_platform',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='来源平台',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('room_orders', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='开始时间',
               existing_nullable=True)
    op.alter_column('room_orders', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='结束时间',
               existing_nullable=True)
    op.alter_column('room_orders', 'duration_minute',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='总时长，单位分钟',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('room_orders', 'order_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='房间单价',
               existing_nullable=True)
    op.alter_column('room_orders', 'renew_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='续单单价',
               existing_nullable=True)
    op.alter_column('room_orders', 'package_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='套餐名称',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('room_orders', 'package_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='套餐总价',
               existing_nullable=True)
    op.alter_column('room_orders', 'package_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='套餐ID',
               existing_nullable=True)
    op.alter_column('room_orders', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='总价',
               existing_nullable=True)
    op.alter_column('room_orders', 'pay_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='实际付款金额',
               existing_nullable=True)
    op.alter_column('room_orders', 'order_status',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='订单状态：created/paid/finished/canceled/refunding/refunded',
               existing_nullable=False,
               existing_server_default=sa.text("'created'::character varying"))
    op.alter_column('room_orders', 'remark',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='下单备注',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('room_orders', 'pay_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='支付时间',
               existing_nullable=True)
    op.alter_column('room_orders', 'finish_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('room_orders', 'cancel_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='取消时间',
               existing_nullable=True)
    op.alter_column('room_orders', 'refund_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='退款时间',
               existing_nullable=True)
    op.alter_column('room_orders', 'pay_channel',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='支付渠道：wechat/alipay/bank/cash/other',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('room_orders', 'refund_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='退款金额，支持部分退款',
               existing_nullable=True)
    op.alter_column('room_orders', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('room_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('room_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('room_orders', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='删除时间（软删时记录）',
               existing_nullable=True)
    op.drop_index(op.f('room_orders_order_number_uidx'), table_name='room_orders', postgresql_where='(is_deleted = false)')
    op.drop_table_comment(
        'room_orders',
        existing_comment='房间订单',
        schema=None
    )
    op.alter_column('rooms', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('rooms', 'shop_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='所属店铺ID',
               existing_nullable=False)
    op.alter_column('rooms', 'room_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='房间名',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('rooms', 'room_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='房间类型（办公/会议/休息等）',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('rooms', 'room_area',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='房间面积',
               existing_nullable=True)
    op.alter_column('rooms', 'capacity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='容量（适用人数）',
               existing_nullable=True)
    op.alter_column('rooms', 'base_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='房间 1 小时单价',
               existing_nullable=True)
    op.alter_column('rooms', 'renew_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='续单 1 小时单价',
               existing_nullable=True)
    op.alter_column('rooms', 'room_status',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='房间状态（空闲/占用/维修/下线/预订等）',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('rooms', 'room_images',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='房间图片列表',
               existing_nullable=False,
               existing_server_default=sa.text('ARRAY[]::text[]'))
    op.alter_column('rooms', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='房间描述',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('rooms', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rooms', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='删除时间（软删时记录）',
               existing_nullable=True)
    op.drop_table_comment(
        'rooms',
        existing_comment='房间信息',
        schema=None
    )
    op.alter_column('shops', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('shops', 'merchant_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='所属商家ID',
               existing_nullable=False)
    op.alter_column('shops', 'shop_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='店铺名',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'contact_name',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='联系人',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'shop_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='门店类型（自营/加盟/共享/品牌联营等）',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'contact_phone',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='联系人电话',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'province',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='省',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'province_code',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='省级行政区划代码',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'city',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='市',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'city_code',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='市级行政区划代码',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='区/县',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'district_code',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='区县级行政区划代码',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'street',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='街道',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'street_code',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='街道级区划代码',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'address',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='详细地址',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='纬度',
               existing_nullable=True)
    op.alter_column('shops', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='经度',
               existing_nullable=True)
    op.alter_column('shops', 'geohash',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='地理位置 geohash',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'business_status',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='营业状态（营业、歇业等）',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'shop_images',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='店铺图片列表',
               existing_nullable=False,
               existing_server_default=sa.text('ARRAY[]::text[]'))
    op.alter_column('shops', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='标签列表',
               existing_nullable=False,
               existing_server_default=sa.text('ARRAY[]::text[]'))
    op.alter_column('shops', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='门店描述',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('shops', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('shops', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shops', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shops', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='删除时间（软删时记录）',
               existing_nullable=True)
    op.drop_table_comment(
        'shops',
        existing_comment='店铺信息',
        schema=None
    )
    op.alter_column('user_auths', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('user_auths', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_auths', 'platform',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='平台（wechat/douyin/kuaishou 等）',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('user_auths', 'openid',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='平台 openid',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('user_auths', 'unionid',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='平台 unionid',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('user_auths', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_auths', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_auths', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_auths', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='删除时间（软删时记录）',
               existing_nullable=True)
    op.drop_table_comment(
        'user_auths',
        existing_comment='用户授权信息（第三方平台绑定）',
        schema=None
    )
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='手机号',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='昵称',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='头像 URL',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'gender',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='性别：0 未知，1 男，2 女',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'birthday',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='生日',
               existing_nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='删除时间（软删时记录）',
               existing_nullable=True)
    op.drop_table_comment(
        'users',
        existing_comment='用户信息',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        '用户信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间（软删时记录）',
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'birthday',
               existing_type=sa.DATE(),
               comment='生日',
               existing_nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.INTEGER(),
               comment='性别：0 未知，1 男，2 女',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=512),
               comment='头像 URL',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=128),
               comment='昵称',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(length=32),
               comment='手机号',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.create_table_comment(
        'user_auths',
        '用户授权信息（第三方平台绑定）',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user_auths', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间（软删时记录）',
               existing_nullable=True)
    op.alter_column('user_auths', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_auths', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_auths', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_auths', 'unionid',
               existing_type=sa.VARCHAR(length=128),
               comment='平台 unionid',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('user_auths', 'openid',
               existing_type=sa.VARCHAR(length=128),
               comment='平台 openid',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('user_auths', 'platform',
               existing_type=sa.VARCHAR(length=16),
               comment='平台（wechat/douyin/kuaishou 等）',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('user_auths', 'user_id',
               existing_type=sa.BIGINT(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_auths', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.create_table_comment(
        'shops',
        '店铺信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('shops', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间（软删时记录）',
               existing_nullable=True)
    op.alter_column('shops', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shops', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shops', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('shops', 'description',
               existing_type=sa.TEXT(),
               comment='门店描述',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('shops', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment='标签列表',
               existing_nullable=False,
               existing_server_default=sa.text('ARRAY[]::text[]'))
    op.alter_column('shops', 'shop_images',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment='店铺图片列表',
               existing_nullable=False,
               existing_server_default=sa.text('ARRAY[]::text[]'))
    op.alter_column('shops', 'business_status',
               existing_type=sa.VARCHAR(length=16),
               comment='营业状态（营业、歇业等）',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'geohash',
               existing_type=sa.VARCHAR(length=32),
               comment='地理位置 geohash',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='经度',
               existing_nullable=True)
    op.alter_column('shops', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='纬度',
               existing_nullable=True)
    op.alter_column('shops', 'address',
               existing_type=sa.VARCHAR(length=255),
               comment='详细地址',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'street_code',
               existing_type=sa.VARCHAR(length=16),
               comment='街道级区划代码',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'street',
               existing_type=sa.VARCHAR(length=255),
               comment='街道',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'district_code',
               existing_type=sa.VARCHAR(length=16),
               comment='区县级行政区划代码',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'district',
               existing_type=sa.VARCHAR(length=64),
               comment='区/县',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'city_code',
               existing_type=sa.VARCHAR(length=16),
               comment='市级行政区划代码',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'city',
               existing_type=sa.VARCHAR(length=64),
               comment='市',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'province_code',
               existing_type=sa.VARCHAR(length=16),
               comment='省级行政区划代码',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'province',
               existing_type=sa.VARCHAR(length=64),
               comment='省',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'contact_phone',
               existing_type=sa.VARCHAR(length=32),
               comment='联系人电话',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'shop_type',
               existing_type=sa.VARCHAR(length=32),
               comment='门店类型（自营/加盟/共享/品牌联营等）',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'contact_name',
               existing_type=sa.VARCHAR(length=128),
               comment='联系人',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'shop_name',
               existing_type=sa.VARCHAR(length=255),
               comment='店铺名',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('shops', 'merchant_id',
               existing_type=sa.BIGINT(),
               comment='所属商家ID',
               existing_nullable=False)
    op.alter_column('shops', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.create_table_comment(
        'rooms',
        '房间信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('rooms', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间（软删时记录）',
               existing_nullable=True)
    op.alter_column('rooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rooms', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('rooms', 'description',
               existing_type=sa.TEXT(),
               comment='房间描述',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('rooms', 'room_images',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               comment='房间图片列表',
               existing_nullable=False,
               existing_server_default=sa.text('ARRAY[]::text[]'))
    op.alter_column('rooms', 'room_status',
               existing_type=sa.VARCHAR(length=16),
               comment='房间状态（空闲/占用/维修/下线/预订等）',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('rooms', 'renew_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='续单 1 小时单价',
               existing_nullable=True)
    op.alter_column('rooms', 'base_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='房间 1 小时单价',
               existing_nullable=True)
    op.alter_column('rooms', 'capacity',
               existing_type=sa.INTEGER(),
               comment='容量（适用人数）',
               existing_nullable=True)
    op.alter_column('rooms', 'room_area',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='房间面积',
               existing_nullable=True)
    op.alter_column('rooms', 'room_type',
               existing_type=sa.VARCHAR(length=32),
               comment='房间类型（办公/会议/休息等）',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('rooms', 'room_name',
               existing_type=sa.VARCHAR(length=255),
               comment='房间名',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('rooms', 'shop_id',
               existing_type=sa.BIGINT(),
               comment='所属店铺ID',
               existing_nullable=False)
    op.alter_column('rooms', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.create_table_comment(
        'room_orders',
        '房间订单',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('room_orders_order_number_uidx'), 'room_orders', ['order_number'], unique=True, postgresql_where='(is_deleted = false)')
    op.alter_column('room_orders', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间（软删时记录）',
               existing_nullable=True)
    op.alter_column('room_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('room_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('room_orders', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('room_orders', 'refund_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='退款金额，支持部分退款',
               existing_nullable=True)
    op.alter_column('room_orders', 'pay_channel',
               existing_type=sa.VARCHAR(length=4),
               comment='支付渠道：wechat/alipay/bank/cash/other',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('room_orders', 'refund_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='退款时间',
               existing_nullable=True)
    op.alter_column('room_orders', 'cancel_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='取消时间',
               existing_nullable=True)
    op.alter_column('room_orders', 'finish_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='完成时间',
               existing_nullable=True)
    op.alter_column('room_orders', 'pay_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='支付时间',
               existing_nullable=True)
    op.alter_column('room_orders', 'remark',
               existing_type=sa.VARCHAR(length=200),
               comment='下单备注',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('room_orders', 'order_status',
               existing_type=sa.VARCHAR(length=8),
               comment='订单状态：created/paid/finished/canceled/refunding/refunded',
               existing_nullable=False,
               existing_server_default=sa.text("'created'::character varying"))
    op.alter_column('room_orders', 'pay_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='实际付款金额',
               existing_nullable=True)
    op.alter_column('room_orders', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='总价',
               existing_nullable=True)
    op.alter_column('room_orders', 'package_id',
               existing_type=sa.BIGINT(),
               comment='套餐ID',
               existing_nullable=True)
    op.alter_column('room_orders', 'package_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='套餐总价',
               existing_nullable=True)
    op.alter_column('room_orders', 'package_name',
               existing_type=sa.VARCHAR(length=50),
               comment='套餐名称',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('room_orders', 'renew_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='续单单价',
               existing_nullable=True)
    op.alter_column('room_orders', 'order_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='房间单价',
               existing_nullable=True)
    op.alter_column('room_orders', 'duration_minute',
               existing_type=sa.INTEGER(),
               comment='总时长，单位分钟',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('room_orders', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='结束时间',
               existing_nullable=True)
    op.alter_column('room_orders', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='开始时间',
               existing_nullable=True)
    op.alter_column('room_orders', 'source_platform',
               existing_type=sa.VARCHAR(length=8),
               comment='来源平台',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('room_orders', 'order_type',
               existing_type=sa.VARCHAR(length=8),
               comment='订单类型：package/hourly',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('room_orders', 'room_id',
               existing_type=sa.BIGINT(),
               comment='房间ID',
               existing_nullable=True)
    op.alter_column('room_orders', 'shop_id',
               existing_type=sa.BIGINT(),
               comment='门店ID',
               existing_nullable=True)
    op.alter_column('room_orders', 'user_id',
               existing_type=sa.BIGINT(),
               comment='下单人ID',
               existing_nullable=True)
    op.alter_column('room_orders', 'ref_id',
               existing_type=sa.BIGINT(),
               comment='续单时为主订单主键ID，新单为 null',
               existing_nullable=True)
    op.alter_column('room_orders', 'order_number',
               existing_type=sa.VARCHAR(length=50),
               comment='生成的订单号',
               existing_nullable=False)
    op.alter_column('room_orders', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.create_table_comment(
        'order_discounts',
        '订单优惠信息（订单关联的优惠券等）',
        existing_comment=None,
        schema=None
    )
    op.alter_column('order_discounts', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间（软删时记录）',
               existing_nullable=True)
    op.alter_column('order_discounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_discounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_discounts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('order_discounts', 'discount_reason',
               existing_type=sa.VARCHAR(length=200),
               comment='优惠原因',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('order_discounts', 'external_platform',
               existing_type=sa.VARCHAR(length=16),
               comment='外部券平台：meituan/douyin 等',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('order_discounts', 'coupon_id',
               existing_type=sa.BIGINT(),
               comment='优惠券ID',
               existing_nullable=True)
    op.alter_column('order_discounts', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='优惠金额',
               existing_nullable=True)
    op.alter_column('order_discounts', 'discount_type',
               existing_type=sa.VARCHAR(length=8),
               comment='优惠类型：balance/coupon/group/external',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('order_discounts', 'order_id',
               existing_type=sa.BIGINT(),
               comment='订单ID',
               existing_nullable=True)
    op.alter_column('order_discounts', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.create_table_comment(
        'merchants',
        '商家入驻信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('merchants', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间（软删时记录）',
               existing_nullable=True)
    op.alter_column('merchants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('merchants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('merchants', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('merchants', 'company_type',
               existing_type=sa.VARCHAR(length=32),
               comment='公司类型（如自营、非自营等）',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('merchants', 'contact_mobile',
               existing_type=sa.VARCHAR(length=32),
               comment='联系人手机号',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('merchants', 'contact_name',
               existing_type=sa.VARCHAR(length=128),
               comment='联系人',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('merchants', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment='公司名',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('merchants', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    # ### end Alembic commands ###
