"""new table

Revision ID: 5ff9356157f3
Revises: f6037626343d
Create Date: 2026-04-02 18:50:24.344213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff9356157f3'
down_revision: Union[str, Sequence[str], None] = 'f6037626343d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False, comment='主键，自增'),
    sa.Column('role_name', sa.String(length=255), server_default='', nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=255), server_default='', nullable=False, comment='角色描述'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删时记录）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间，插入时自动赋值'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间，更新时自动赋值'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False, comment='主键，自增'),
    sa.Column('tenant_name', sa.String(length=255), server_default='', nullable=False, comment='租户名称'),
    sa.Column('code', sa.String(length=128), server_default='', nullable=False, comment='租户唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删时记录）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间，插入时自动赋值'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间，更新时自动赋值'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tenants',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False, comment='主键，自增'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删时记录）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间，插入时自动赋值'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间，更新时自动赋值'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False, comment='主键，自增'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('shop_id', sa.BigInteger(), nullable=False, comment='店铺ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删时记录）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间，插入时自动赋值'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间，更新时自动赋值'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_roles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False, comment='主键，自增'),
    sa.Column('employee_id', sa.BigInteger(), nullable=False, comment='员工ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('shop_id', sa.BigInteger(), nullable=True, comment='可选：不同角色在不同门店生效'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删时记录）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间，插入时自动赋值'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间，更新时自动赋值'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('merchants', sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'))
    op.create_foreign_key(None, 'merchants', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('room_orders', sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'))
    op.create_foreign_key(None, 'room_orders', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('rooms', sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'))
    op.create_foreign_key(None, 'rooms', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('shops', sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'))
    op.create_foreign_key(None, 'shops', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('users', sa.Column('password', sa.String(length=255), server_default='', nullable=False, comment='密码'))
    op.add_column('users', sa.Column('email', sa.String(length=255), server_default='', nullable=False, comment='邮箱'))
    op.add_column('users', sa.Column('username', sa.String(length=128), server_default='', nullable=False, comment='用户名'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_column('users', 'email')
    op.drop_column('users', 'password')
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'tenant_id')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'tenant_id')
    op.drop_constraint(None, 'room_orders', type_='foreignkey')
    op.drop_column('room_orders', 'tenant_id')
    op.drop_constraint(None, 'merchants', type_='foreignkey')
    op.drop_column('merchants', 'tenant_id')
    op.drop_table('employee_roles')
    op.drop_table('employees')
    op.drop_table('user_tenants')
    op.drop_table('tenants')
    op.drop_table('roles')
    # ### end Alembic commands ###
