"""remove tenant support 

Revision ID: 86b00c7a4dca
Revises: 9a6b3f5e2d11
Create Date: 2026-04-17 18:56:24.322347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b00c7a4dca'
down_revision: Union[str, Sequence[str], None] = '9a6b3f5e2d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
