"""add user token

Revision ID: b2ac5ad13bd6
Revises: 437e00ed428c
Create Date: 2026-04-03 21:27:10.957204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ac5ad13bd6'
down_revision: Union[str, Sequence[str], None] = '437e00ed428c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tokens',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False, comment='主键，自增'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('login_type', sa.String(length=16), server_default='', nullable=False, comment='登录类型（password/sms/wechat/douyin/kuaishou 等）'),
    sa.Column('jti', sa.String(length=255), server_default='', nullable=False, comment='jti'),
    sa.Column('refresh_token_hash', sa.String(length=255), server_default='', nullable=False, comment='refresh_token_hash'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.Column('platform', sa.String(length=16), server_default='', nullable=False, comment='平台（wechat/douyin/kuaishou 等）'),
    sa.Column('user_agent', sa.String(length=255), server_default='', nullable=False, comment='用户代理'),
    sa.Column('ip', sa.String(length=255), server_default='', nullable=False, comment='IP地址'),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False, comment='是否已撤销'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='撤销时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='是否删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删时记录）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间，插入时自动赋值'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间，更新时自动赋值'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tokens')
    # ### end Alembic commands ###
