"""new model

Revision ID: ecf0b671791d
Revises: b2ac5ad13bd6
Create Date: 2026-04-04 18:45:32.375897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecf0b671791d'
down_revision: Union[str, Sequence[str], None] = 'b2ac5ad13bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_roles', 'id',
               existing_type=sa.BIGINT(),
               comment='主键ID',
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('employee_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'id',
               existing_type=sa.BIGINT(),
               comment='主键ID',
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('merchants', 'id',
               existing_type=sa.BIGINT(),
               comment='主键ID',
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('merchants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('merchants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_discounts', 'id',
               existing_type=sa.BIGINT(),
               comment='主键ID',
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('order_discounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_discounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'id',
               existing_type=sa.BIGINT(),
               comment='主键ID',
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('room_orders', 'id',
               existing_type=sa.BIGINT(),
               comment='主键ID',
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('room_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('room_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rooms', 'id',
               existing_type=sa.BIGINT(),
               comment='主键ID',
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shops', 'id',
               existing_type=sa.BIGINT(),
               comment='主键ID',
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('shops', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shops', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'id',
               existing_type=sa.BIGINT(),
               comment='主键ID',
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_auths', 'id',
               existing_type=sa.BIGINT(),
               comment='主键ID',
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('user_auths', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_auths', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_tenants', 'id',
               existing_type=sa.BIGINT(),
               comment='主键ID',
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('user_tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_tokens', 'id',
               existing_type=sa.BIGINT(),
               comment='主键ID',
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('user_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               comment='主键ID',
               existing_comment='主键，自增',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_comment='创建时间，插入时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_comment='更新时间，更新时自动赋值',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_comment='主键ID',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('user_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_tokens', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_comment='主键ID',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('user_tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_tenants', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_comment='主键ID',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('user_auths', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_auths', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_auths', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_comment='主键ID',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_comment='主键ID',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('shops', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shops', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shops', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_comment='主键ID',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('rooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rooms', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_comment='主键ID',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('room_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('room_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('room_orders', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_comment='主键ID',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_comment='主键ID',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('order_discounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_discounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_discounts', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_comment='主键ID',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('merchants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('merchants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('merchants', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_comment='主键ID',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_comment='主键ID',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('employee_roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间，更新时自动赋值',
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间，插入时自动赋值',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employee_roles', 'id',
               existing_type=sa.BIGINT(),
               comment='主键，自增',
               existing_comment='主键ID',
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    # ### end Alembic commands ###
